package:
  name: spiceql
  version: 0.0.1 # {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: https://github.com/USGS-Astrogeology/SpiceQL.git
build:
  string: {{ environ.get("GIT_DESCRIBE_HASH", "") }}

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - cmake >=3.10
    - pip
    - python
    - cspice-cmake
  run:
    - cpp-filesystem
    - fmt
    - ninja
  host:
    - cpp-filesystem
    - fmt
    - ninja

test:
  commands:
    - ctest -j8  # [linux]

about:
  home: https://sugar-spice.readthedocs.io/en/latest/#docs
  license: None
summary: "This Library provides a C++ interface querying, reading and writing Naif SPICE kernels."

