package:
  name: sugarspice
  version: 0.0.1 # {{ environ.get("GIT_DESCRIBE_TAG", "") }}

source:
  git_url: https://github.com/USGS-Astrogeology/SugarSpice.git
build:
  string: {{ environ.get("GIT_DESCRIBE_HASH", "") }}

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux]
    - vc 14  # [win]
    - cmake >=3.10
#    - cspice-cmake
  run:
    - vc  # [win]
    - cpp-filesystem
    - doxygen
    - fmt
    - ninja
    - pip
    - python

test:
  commands:
    - ctest -j8  # [linux]

about:
  home: https://sugar-spice.readthedocs.io/en/latest/#docs
  license: None
summary: "This Library provides a C++ interface querying, reading and writing Naif SPICE kernels."

