channels:
  - tudat-team
  - defaults
  - conda-forge
  - usgs-astrogeology

dependencies:
  - cmake 
  - cspice-cmake
  - cpp-filesystem
  - doxygen
  - fmt
  - ninja
  - pip
  - python
  - pip:
    - breathe
    - sphinx-material
    - m2r2
    - sphinxcontrib.gist
